### ISSUE TITLE
Chart fails to deploy with empty stardog.properties

### ISSUE THREAD

**Issue by snowell** [stardog-union/helm-charts#31] opened 2020-10-15 12:22 UTC
If your stardog.properties file is completely empty, the helm chart will fail to deploy, i think it expects at least 1 key=value pair. The exact error I get is

```
Error: YAML parse error on novacontext-chart/charts/stardog/templates/configmap.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key
```

We discovered this as a result of a postprocessor we have that inserts a different stardog.properties file at the last minute, the one we inserted was blank, if we insert one with a random pair "key=value" it works. if blank, it fails, if we delete it at the last minute, it also fails with the same error

**Comment by pdmars** [comment] 2020-12-14 15:54
Closing since I'm not able to reproduce. Please reopen if this happens again and provide any steps required to reproduce it.

**Closed as completed by pdmars** 2020-12-14 15:54 UTC
Labels: cannot reproduce
